## Week 2: Jupyter Notebook - Pandas Introduction/Overview
Make sure to select your Kernel before starting!

Watch the [Youtube Video](https://www.youtube.com/watch?v=DkjCaAMBGWM&t=1s) I based this notebook from!

### Import Pandas Library/Package
`import pandas as pd`

In [ ]:
import pandas as pd

### Optional: Displaying your Dataframe
Don't use for big datasets

In [ ]:
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.max_rows", None)     # Show all rows

### How to make a dataframe
`pd.DataFrame()`

In [ ]:
data = {'Name': ['Zophie', 'Alice', 'Bob', 'Charlie'], 
        'Age': [7, 5, 3, 2],
        'Color': ['Gray', 'Black', 'Brown', 'White']
        }  

data                                                     # Called a Python Dictionary

#### Create a data frame
Store the dataframe using the `pd.DataFrame()` function into a variable called `df`

In [ ]:
df = pd.DataFrame(data)
df

### Read In Datasets
`pd.read_csv()`
Read in the file from the data folder called `Shot_Visuals_KaylanBigun_NathanTrouve.csv`

Save as `shots`

In [ ]:
shots = pd.read_csv("data/Shot_Visuals_KaylanBigun_NathanTrouve.csv")

`pd.read_json()`

`pd.read_excel(x, sheet_name)`

In [ ]:
shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name='Shots')

### Basic Functions for Quick Analysis
`df.head()`

Gives you the **FIRST** 5 observations/rows
- If you put a number within the parentheses you will get that number of rows

In [ ]:
shots.head()

`df.tail()`
Gives you the **LAST** 5 observations/rows

In [ ]:
shots.tail()

`df.sample()`

Gives you a **RANDOM** observation sample

Arguments: frac, random_state

In [ ]:
shots.sample()

`df.columns`

Gives you all the column names of your dataset

In [ ]:
shots.columns

In [ ]:
shots_excel.columns

`df.index`

Gives you the index values in the dataframe

In [ ]:
shots.index

Use the `list()` function to see all the numbers

In [ ]:
list(shots.index)

`df.info()`

In [ ]:
shots.info()

`df.describe()`

In [ ]:
shots.describe()

`df.shape`

In [ ]:
shots.shape

`len()`

In [ ]:
len(shots)

In [ ]:
sample_data = range(0, 10)
len(sample_data)
list(sample_data)

In [ ]:
sample_data = data['Name']
len(sample_data)
data['Name']

### How to Subset your Dataframe
One Column: `df[]`

Multiple Columns: `df[[ ]]`

In [ ]:
shots['pointScore']
shots[['pointScore']]

In [ ]:
shots[['pointScore', 'gameScore']]

### How to Filter your dataframe

`df.loc[]` and `df.iloc[]`

`df.loc[df['column'] == 'condition']`

In [ ]:
shots.loc[shots['InsideOut'] == 1].head()

In [ ]:
shots.head()

In [ ]:
shots.iloc[0,4]

### Conditional Subsetting & Querying
`&`

`|`

In [ ]:
shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['isAce'] == 1)]

In [ ]:
shots_excel.head()

`.query()`
1. Filter when the `serverName` is equal to `Kaylan Bigun`
2. Also Filter all of his Aces

Can use many conditions (==, != , >, <, >=, <=)

In [ ]:

shots.query('serverName == "Kaylan Bigun" and isAce == 1')

In [119]:
shots_excel.query("`Speed (MPH)` > 100")

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
6,Kaylan Bigun,1,second_serve,Serve,Flat,110.786316,2,1,1,deep,ad,far,2.284124,19.640869,deep,ad,near,-2.001953,0.623191,2.349609,down the T,Out,False,22:46:43,104.949997
11,Nathan Trouve,1,first_serve,Serve,Flat,115.043945,4,1,1,deep,ad,far,2.898438,18.296926,deep,ad,near,-1.217773,0.203817,2.269531,out wide,Out,False,22:48:03,184.279999
17,Nathan Trouve,1,second_serve,Serve,Slice,120.689171,5,2,1,deep,deuce,far,-1.173526,21.427223,deep,deuce,near,0.915527,0.252415,2.164062,down the T,Out,False,22:48:40,221.880005
22,Nathan Trouve,1,first_serve,Serve,Slice,110.410797,7,2,1,short,deuce,far,-1.324739,18.212114,deep,deuce,near,1.223633,0.615378,2.371094,down the T,In,False,22:49:28,269.149994
33,Nathan Trouve,1,first_serve,Serve,Kick,103.583366,8,2,1,deep,deuce,far,-0.481523,20.106646,deep,ad,near,-1.806641,0.427878,2.490234,down the T,Out,False,22:49:58,299.350006
38,Kaylan Bigun,1,first_serve,Serve,Flat,126.093613,9,3,1,short,deuce,near,0.905529,8.206503,deep,deuce,far,-0.231567,22.740038,2.203125,down the T,In,False,22:50:38,339.079987
44,Kaylan Bigun,1,first_serve,Serve,Flat,121.144768,11,3,1,deep,deuce,near,0.520290,5.436885,deep,deuce,far,-0.210938,23.365038,1.617188,down the T,Out,False,22:51:32,393.049988
52,Kaylan Bigun,1,first_serve,Serve,Flat,108.255554,12,3,1,short,deuce,near,0.788065,7.590147,deep,ad,far,1.255859,23.542282,2.300781,down the T,Out,False,22:52:13,434.079987
104,Kaylan Bigun,1,first_serve,Serve,Flat,101.224380,24,5,1,short,ad,far,0.850903,18.208048,deep,ad,near,-1.506836,0.584128,2.279297,down the T,In,False,22:59:55,896.340027
111,Kaylan Bigun,1,first_serve,Serve,Flat,112.567017,26,5,1,short,ad,far,0.412697,18.212114,deep,ad,near,-1.662109,0.193503,2.341797,down the T,In,False,23:00:49,950.739990
117,Kaylan Bigun,1,first_serve,Serve,Flat,104.861420,27,5,1,short,ad,far,0.401453,18.273750,deep,deuce,near,0.954590,1.412253,2.310547,down the T,Out,False,23:01:17,978.010010
129,Nathan Trouve,1,first_serve,Serve,Slice,102.068214,31,6,1,short,ad,far,0.295614,18.252337,deep,ad,near,-1.935547,0.466941,2.365234,down the T,In,False,23:04:29,1170.540039
131,Nathan Trouve,1,first_serve,Serve,Kick,105.600487,32,6,1,deep,deuce,far,-3.483063,18.666100,deep,deuce,near,1.046875,0.670066,2.441406,out wide,Out,False,23:04:47,1188.369995
140,Nathan Trouve,1,second_serve,Serve,Slice,107.860924,34,6,1,deep,deuce,far,-0.679553,18.318201,deep,deuce,near,1.118164,1.060691,2.455078,down the T,Out,False,23:05:38,1239.310059
141,Nathan Trouve,1,first_serve,Serve,Kick,107.522804,35,6,1,deep,ad,far,2.775662,20.479452,deep,ad,near,-1.673828,0.459128,2.291016,out wide,Out,False,23:06:06,1267.109985
184,Nathan Trouve,1,first_serve,Serve,Flat,121.590271,44,8,1,short,deuce,near,1.833858,7.803025,deep,deuce,far,-0.138306,23.289427,2.095703,down the T,In,False,23:12:03,1624.939941
189,Nathan Trouve,1,first_serve,Serve,Flat,108.080238,45,8,1,short,ad,near,-1.188449,6.548457,deep,ad,far,1.015625,23.771288,2.332031,down the T,In,False,23:12:27,1648.300049
201,Kaylan Bigun,1,first_serve,Serve,Slice,104.336891,49,9,1,short,ad,far,3.348177,18.225574,deep,ad,near,-1.978516,0.660815,2.195312,out wide,In,False,23:14:12,1753.099976
204,Kaylan Bigun,1,first_serve,Serve,Kick,110.256676,50,9,1,short,deuce,far,-0.356118,18.274300,deep,deuce,near,0.978516,0.576316,2.427734,down the T,In,False,23:14:42,1783.300049
211,Kaylan Bigun,1,first_serve,Serve,Flat,110.967171,51,9,1,short,ad,far,1.309921,18.263353,deep,ad,near,-1.694336,0.631003,2.226562,down the T,In,False,23:15:28,1829.300049
238,Nathan Trouve,1,first_serve,Serve,Slice,106.472656,55,10,1,short,ad,far,0.885615,18.267567,deep,deuce,near,1.059570,1.131003,2.287109,down the T,Out,False,23:18:46,2027.900024
243,Nathan Trouve,1,first_serve,Serve,Flat,100.548752,56,10,1,deep,ad,far,1.196801,19.588367,deep,ad,near,-1.653320,0.646628,2.228516,down the T,Out,False,23:19:42,2083.399902
255,Nathan Trouve,1,first_serve,Serve,Slice,117.086929,58,10,1,deep,ad,far,4.040221,23.042145,deep,ad,near,-1.418945,-0.095559,2.439453,out wide,Out,False,23:20:41,2142.929932
265,Nathan Trouve,1,second_serve,Serve,Slice,122.938042,59,10,1,deep,deuce,far,-2.053125,18.320839,deep,deuce,near,1.021484,0.584128,2.494141,down the T,Out,False,23:21:47,2208.030029
273,Kaylan Bigun,1,first_serve,Serve,Flat,101.018517,61,11,1,short,ad,near,-1.121347,7.747947,deep,ad,far,1.778320,23.099413,2.408203,down the T,In,False,23:22:40,2261.449951
281,Kaylan Bigun,1,first_serve,Serve,Kick,129.921982,62,11,1,short,deuce,near,0.538454,6.110898,deep,deuce,far,-0.120850,23.365038,2.187500,down the T,In,False,23:23:37,2318.330078
283,Kaylan Bigun,1,first_serve,Serve,Flat,116.459045,63,11,1,short,ad,near,-3.930593,8.373328,deep,ad,far,1.526367,22.802538,2.431641,out wide,In,False,23:23:55,2336.060059
285,Kaylan Bigun,1,first_serve,Serve,Flat,117.086929,64,11,1,short,deuce,near,2.594978,7.929790,deep,deuce,far,-0.209595,23.208788,2.279297,out wide,In,False,23:24:30,2371.629883
339,Nathan Trouve,1,first_serve,Serve,Flat,103.576897,72,12,1,short,ad,near,-1.631332,7.742897,out,ad,far,1.351562,25.021288,2.343750,down the T,In,False,23:29:54,2695.590088
372,Nathan Trouve,1,first_serve,Serve,Flat,104.454910,79,14,2,short,ad,far,3.978534,17.177071,deep,ad,near,-0.554199,0.956273,1.970703,out wide,In,False,23:36:21,3082.949951
379,Nathan Trouve,1,first_serve,Serve,Slice,119.513947,82,14,2,deep,deuce,far,-1.039617,21.247305,deep,deuce,near,0.832031,0.257688,2.066406,down the T,Out,False,23:37:51,3172.719971
381,Nathan Trouve,1,second_serve,Serve,Slice,101.285225,82,14,2,short,deuce,far,-3.392186,17.784779,deep,deuce,near,0.697266,0.454843,2.160156,out wide,In,False,23:38:04,3185.250000
385,Kaylan Bigun,1,first_serve,Serve,Flat,130.596954,83,15,2,deep,deuce,near,0.487283,5.429316,deep,deuce,far,-0.148071,23.620859,1.673828,down the T,Out,False,23:38:30,3211.649902
400,Kaylan Bigun,1,first_serve,Serve,Kick,126.093613,85,15,2,short,center_line,near,0.021474,6.309115,deep,deuce,far,-0.291992,23.880663,2.285156,down the T,In,False,23:40:05,3306.820068
401,Kaylan Bigun,1,second_serve,Serve,Flat,101.416885,85,15,2,short,deuce,near,3.378550,8.166207,deep,deuce,far,-0.551270,24.146288,2.343750,out wide,In,False,23:40:19,3320.290039
407,Kaylan Bigun,1,first_serve,Serve,Flat,109.630287,86,15,2,short,deuce,near,0.128755,6.946786,deep,ad,far,1.441406,23.052538,2.351562,down the T,Out,False,23:40:58,3359.550049
410,Kaylan Bigun,1,first_serve,Serve,Flat,101.115784,87,15,2,deep,deuce,near,0.050919,4.808718,deep,deuce,far,-0.391357,24.240038,2.337891,down the T,Out,False,23:41:38,3399.250000
429,Nathan Trouve,1,first_serve,Serve,Flat,103.576897,91,16,2,short,deuce,near,0.915160,6.877904,deep,deuce,far,-0.771973,22.927538,2.462891,down the T,In,False,23:44:39,3580.679932
463,Kaylan Bigun,1,first_serve,Serve,Slice,105.956909,100,17,2,deep,deuce_alley,far,-4.569581,22.181734,deep,deuce,near,0.919434,1.115378,2.416016,out wide,Out,False,23:48:40,3821.909912
477,Nathan Trouve,1,first_serve,Serve,Flat,110.563896,104,18,2,short,ad,far,0.633726,18.195896,deep,ad,near,-1.747070,0.545066,2.318359,down the T,In,False,23:52:04,4025.709961
485,Kaylan Bigun,1,first_serve,Serve,Flat,106.193489,106,19,2,short,ad,near,-1.111097,7.986207,deep,ad,far,1.619141,23.380791,2.435547,down the T,In,False,23:52:51,4072.209961
496,Kaylan Bigun,1,first_serve,Serve,Flat,118.787109,107,19,2,short,deuce,near,0.255883,8.012415,deep,deuce,far,-0.351318,23.755663,2.283203,down the T,In,False,23:53:39,4120.439941
500,Kaylan Bigun,1,first_serve,Serve,Flat,126.093613,108,19,2,short,ad,near,-0.727706,5.707966,deep,ad,far,1.315430,23.192524,2.359375,down the T,In,False,23:54:13,4154.740234
507,Kaylan Bigun,1,first_serve,Serve,Flat,126.866127,111,19,2,short,deuce,near,0.627582,7.555522,deep,ad,far,0.224854,22.568163,1.506836,down the T,Out,False,23:55:36,4237.740234
539,Nathan Trouve,1,first_serve,Serve,Flat,108.220818,115,20,2,short,ad,near,-1.588268,7.398328,deep,ad,far,1.132812,22.286913,2.345703,down the T,In,False,23:58:52,4433.919922

### Summarizing the Data (Numerical)
`.mean()`

`.max()`

`.min()`

`.std()`

`.var()`

`.quantile`

In [ ]:
shots_excel['Speed (MPH)'].max()

### Can also do for multiple Columns
`df[['column', 'column', ...]].mean()`

In [ ]:
shots_excel[['Speed (MPH)','Bounce (x)']].max()

### Use the Aggregate Function

`.agg()`

`df[['column', 'column', ...]].agg(['mean', 'sum', 'max'])`

In [114]:
shots_excel[['Speed (MPH)','Bounce (x)']].agg(['mean', 'sum'])

       Speed (MPH)  Bounce (x)
mean     60.699205   -0.034155
sum   33020.367540  -18.580325

`.sum()`

In [ ]:
shots_excel['Speed (MPH)'].sum()

`.count()`

In [ ]:
shots_excel['Speed (MPH)'].count()
shots_excel.shape

### Summarizing the Data (Categorial)

`.unique()`

In [ ]:
shots_excel['Stroke'].unique()
shots_excel.loc[shots_excel['Stroke'] == 'Feed']

`.nunique()`

Same as len(df.unique())

In [ ]:
shots_excel['Stroke'].nunique()

`.value_counts()`

Arguments: normalize (True, False)


Find the value counts of `firstServeZone`

Find the value counts of `firstServeZone` and `firstServeIn`

In [ ]:
shots_excel['Stroke'].value_counts(normalize=True)

### GroupBy Methods
`df.groupby()`

In [ ]:
shots.groupby('pointNumber')['InsideOut'].sum()
#shots[shots['pointNumber'] == 80]

### Handling Missing Values
`.isna()`

`.dropna()`

`.fillna()`

In [ ]:
shots.isna().sum()

### How to save/write your CSV
`.to_csv()`

In [ ]:
#df.to_csv('cats.csv')

### Problems to Practice Yourself!!

#### Problem 1: From the `Shot_Visuals_KaylanBigun_NathanTrouve.csv` dataset, create two tables
1. Table of the **counts** of the zones Kaylan had served into for his firstServe (including made adn missed)
1. Table of the **percentage** of the zones Kaylan had served into for his firstServe ((including made adn missed))

In [108]:
# Subsetting
# Conditional/Querying 
# value_counts()

kaylan_serve_zone_counts = shots[(shots['serverName'] == 'Kaylan Bigun') & (shots['firstServeZone'].notna())]['firstServeZone'].value_counts()
kaylan_serve_zone_counts_table = pd.DataFrame(kaylan_serve_zone_counts)
kaylan_serve_zone_counts_table

kaylan_serve_zone_percent = shots[(shots['serverName'] == 'Kaylan Bigun') & (shots['firstServeZone'].notna())]['firstServeZone'].value_counts(normalize=True)
kaylan_serve_zone_percent_table = pd.DataFrame(kaylan_serve_zone_percent)
kaylan_serve_zone_percent_table

                proportion
firstServeZone
T                 0.532258
Wide              0.306452
Body              0.161290

#### Problem 2: From the `(playsight)kaylan_usc.xlsx` dataset (Download from slack!)
Find the minimum, maximum, and average speed of Kaylan's stroke type

In [118]:
# .agg() (.max(), .mean(), .sum())
# value_counts()

kaylan_excel_shots = shots_excel[shots_excel['Player'] == 'Kaylan Bigun']
kaylan_excel_shots.groupby('Stroke')['Speed (MPH)'].agg(['mean', 'max', 'min'])

               mean         max        min
Stroke
Backhand  49.743167   77.378082  25.032770
Feed      18.490169   21.650688  17.320551
Forehand  51.628206   88.736710  24.667412
Serve     88.299908  130.596954  40.868378
Volley    22.949730   23.382744  22.516716