## Week 2: Jupyter Notebook - Pandas Introduction/Overview
Make sure to select your Kernel before starting!

Watch the [Youtube Video](https://www.youtube.com/watch?v=DkjCaAMBGWM&t=1s) I based this notebook from!

### Import Pandas Library/Package
`import pandas as pd`

In [2]:
import pandas as pd

### Optional: Displaying your Dataframe
Don't use for big datasets

In [3]:
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.max_rows", None)     # Show all rows

### How to make a dataframe
`pd.DataFrame()`

In [4]:
data = {'Name': ['Zophie', 'Alice', 'Bob', 'Charlie'], 
        'Age': [7, 5, 3, 2],
        'Color': ['Gray', 'Black', 'Brown', 'White']
        }                                                       # Called a Python Dictionary

#### Create a data frame
Store the dataframe using the `pd.DataFrame()` function into a variable called `df`

In [5]:
df = pd.DataFrame(data)
df

      Name  Age  Color
0   Zophie    7   Gray
1    Alice    5  Black
2      Bob    3  Brown
3  Charlie    2  White

### Read In Datasets
`pd.read_csv()`
Read in the file from the data folder called `Shot_Visuals_KaylanBigun_NathanTrouve.csv`

Save as `shots`

In [6]:
shots = pd.read_csv('data/Shot_Visuals_KaylanBigun_NathanTrouve.csv')

`pd.read_json()`

`pd.read_excel(x, sheet_name)`

In [32]:
shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name='Shots')

### Basic Functions for Quick Analysis
`df.head()`

Gives you the **FIRST** 5 observations/rows
- If you put a number within the parentheses you will get that number of rows

In [8]:
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

`df.tail()`
Gives you the **LAST** 5 observations/rows

In [9]:
shots.tail()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
467,30-15,2-5,0-1,1.0,4433919.0,NaN,NaN,117,NaN,1,Ad,Nathan Trouve,Far,1.0,Body,-60.793285,-171.818154,NaN,NaN,NaN,NaN,NaN,43.360039,398.064255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,1st Serve In,Body,NaN
468,30-15,2-5,0-1,NaN,4434580.0,NaN,NaN,117,NaN,2,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-122.080988,-434.136800,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.583503,192.648972,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,20,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
469,30-15,2-5,0-1,NaN,4436419.0,NaN,NaN,117,NaN,3,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.231327,439.331070,Down the Line,Backhand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.163774,-243.998803,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
470,30-15,2-5,0-1,NaN,4439640.0,1.0,4439640.0,117,NaN,4,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.187981,228.212440,Down the Line,Forehand,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,149.959230,-172.655184,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,NaN,NaN,NaN
471,40-15,2-5,0-1,1.0,4457669.0,1.0,4457669.0,118,NaN,1,Deuce,Nathan Trouve,Far,1.0,T,12.432847,-233.994483,NaN,NaN,NaN,NaN,1.0,6.873114,449.561909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,Nathan Trouve,NaN,1st Serve In,T,NaN

`df.sample()`

Gives you a **RANDOM** observation sample

Arguments: frac, random_state

In [10]:
shots.sample(5)

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
50,15-30,2-0,0-0,NaN,446959.0,NaN,NaN,14,NaN,3,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-36.071090,419.594767,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.876208,-212.609230,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,3,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
415,15-0,2-4,0-1,NaN,4074129.0,NaN,NaN,108,NaN,3,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-52.293728,469.234558,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.565775,-334.638353,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,19,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
175,0-15,4-4,0-0,1.0,1753099.0,NaN,NaN,51,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,128.156381,242.610553,NaN,NaN,NaN,NaN,NaN,-75.730599,-429.706338,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,9,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,1st Serve In,Wide,NaN
30,30-30,1-0,0-0,NaN,278220.0,NaN,NaN,9,NaN,8,Deuce,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-45.602811,475.215256,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.823628,-341.704112,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,2,NaN,Kaylan Bigun,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
336,0-0,0-2,0-1,NaN,3240949.0,1.0,3240949.0,85,NaN,10,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.440365,-443.406901,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-68.964928,-233.497080,NaN,NaN,NaN,1.0,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,15,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN

`df.columns`

Gives you all the column names of your dataset

In [11]:
shots.columns

Index(['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
       'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
       'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
       'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
       'secondServeIn', 'secondServeZone', 'secondServeXCoord',
       'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
       'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
       'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
       'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
       'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
       'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
       'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
       'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
       'Notes', 'isTopspin', 'isFlat', 'isKick', 'gameNumber', 'tiebreakScore',
       'returnerName', 'shotHitBy', 'InsideOut', 'InsideIn', 'isDoubleFault',
       'pointWonBy', 'lastShotError', 'serveResult', 'serveInPlacement',
       'depth'],
      dtype='object')

`df.index`

Gives you the index values in the dataframe

In [12]:
shots.index

RangeIndex(start=0, stop=472, step=1)

Use the `list()` function to see all the numbers

In [13]:
list(shots.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471]

`df.info()`

In [14]:
shots.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472 entries, 0 to 471
Data columns (total 72 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pointScore         472 non-null    object
 1   gameScore          472 non-null    object
 2   setScore           472 non-null    object
 3   isPointStart       118 non-null    float64
 4   pointStartTime     471 non-null    float64
 5   isPointEnd         118 non-null    float64
 6   pointEndTime       117 non-null    float64
 7   pointNumber        472 non-null    int64
 8   isBreakPoint       81 non-null     float64
 9   shotInRally        472 non-null    int64
 10  side               472 non-null    object
 11  serverName         472 non-null    object
 12  serverFarNear      472 non-null    object
 13  firstServeIn       116 non-null    float64
 14  firstServeZone     116 non-null    object
 15  firstServeXCoord   116 non-null    float64
 16  firstServeYCoord   116 non-null    float64
 17  secondServeIn      45 non-null     float64
 18  secondServeZone    45 non-null     object
 19  secondServeXCoord  45 non-null     float64
 20  secondServeYCoord  45 non-null     float64
 21  isAce              5 non-null      float64
 22  shotContactX       465 non-null    float64
 23  shotContactY       465 non-null    float64
 24  shotDirection      354 non-null    object
 25  shotFhBh           351 non-null    object
 26  isSlice            70 non-null     float64
 27  isVolley           3 non-null      float64
 28  isOverhead         2 non-null      float64
 29  isApproach         1 non-null      float64
 30  isDropshot         1 non-null      float64
 31  isExcitingPoint    0 non-null      float64
 32  atNetPlayer1       3 non-null      float64
 33  atNetPlayer2       1 non-null      float64
 34  isLob              0 non-null      float64
 35  shotLocationX      355 non-null    float64
 36  shotLocationY      355 non-null    float64
 37  isWinner           26 non-null     float64
 38  isErrorWideR       8 non-null      float64
 39  isErrorWideL       10 non-null     float64
 40  isErrorNet         59 non-null     float64
 41  isErrorLong        31 non-null     float64
 42  clientTeam         472 non-null    object
 43  Date               472 non-null    object
 44  Division           472 non-null    object
 45  Event              472 non-null    object
 46  lineupPosition     1 non-null      float64
 47  matchDetails       0 non-null      float64
 48  matchVenue         472 non-null    object
 49  opponentTeam       472 non-null    object
 50  player1Name        472 non-null    object
 51  player2Name        472 non-null    object
 52  player1Hand        472 non-null    object
 53  player2Hand        472 non-null    object
 54  Round              0 non-null      float64
 55  Surface            472 non-null    object
 56  Notes              0 non-null      float64
 57  isTopspin          198 non-null    float64
 58  isFlat             166 non-null    float64
 59  isKick             10 non-null     float64
 60  gameNumber         472 non-null    int64
 61  tiebreakScore      0 non-null      float64
 62  returnerName       472 non-null    object
 63  shotHitBy          472 non-null    object
 64  InsideOut          52 non-null     float64
 65  InsideIn           54 non-null     float64
 66  isDoubleFault      5 non-null      float64
 67  pointWonBy         118 non-null    object
 68  lastShotError      86 non-null     float64
 69  serveResult        118 non-null    object
 70  serveInPlacement   114 non-null    object
 71  depth              274 non-null    object
dtypes: float64(42), int64(3), object(27)
memory usage: 265.6+ KB

`df.describe()`

In [15]:
shots.describe()

,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,firstServeIn,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,lineupPosition,matchDetails,Round,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,InsideOut,InsideIn,isDoubleFault,lastShotError
count,118.0,4.710000e+02,118.0,1.170000e+02,472.000000,81.0,472.000000,116.000000,116.000000,116.000000,45.000000,45.000000,45.000000,5.0,465.000000,465.000000,70.0,3.0,2.0,1.0,1.0,0.0,3.0,1.0,0.0,355.000000,355.000000,26.0,8.0,10.0,59.0,31.0,1.0,0.0,0.0,0.0,198.0,166.0,10.0,472.000000,0.0,52.0,54.0,5.0,86.0
mean,1.0,2.284684e+06,1.0,2.213681e+06,62.103814,1.0,3.508475,0.612069,1.018972,6.278533,0.622222,-0.555828,81.510268,1.0,-1.876645,4.458188,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-2.562345,24.169400,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,10.726695,NaN,1.0,1.0,1.0,1.0
std,0.0,1.311719e+06,0.0,1.325135e+06,33.705478,0.0,2.926548,0.489393,92.930666,214.363255,0.490310,88.823415,204.013913,0.0,95.061139,467.252608,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,91.833594,323.553549,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,5.647415,NaN,0.0,0.0,0.0,0.0
min,1.0,2.502000e+04,1.0,3.854900e+04,1.000000,1.0,1.000000,0.000000,-174.907409,-357.316240,0.000000,-158.068099,-246.000000,1.0,-205.137932,-559.000000,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-212.856419,-564.116366,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.000000,NaN,1.0,1.0,1.0,1.0
25%,1.0,1.211054e+06,1.0,1.057069e+06,35.000000,1.0,1.750000,0.000000,-61.205370,-187.465984,0.000000,-69.107048,-154.447643,1.0,-74.721325,-463.143203,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-79.483648,-276.164348,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,6.000000,NaN,1.0,1.0,1.0,1.0
50%,1.0,2.285176e+06,1.0,2.169659e+06,63.500000,1.0,3.000000,1.000000,9.132191,-113.950990,1.000000,-20.160176,195.738840,1.0,2.667946,223.427882,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-3.123704,8.803128,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,11.000000,NaN,1.0,1.0,1.0,1.0
75%,1.0,3.438290e+06,1.0,3.410780e+06,90.250000,1.0,4.000000,1.000000,50.516820,241.978628,1.000000,73.484843,245.380430,1.0,61.862844,469.234558,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,72.984052,321.674459,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,15.250000,NaN,1.0,1.0,1.0,1.0
max,1.0,4.457669e+06,1.0,4.457669e+06,118.000000,1.0,19.000000,1.000000,183.301438,426.971867,1.000000,179.708809,365.158361,1.0,250.000000,617.555862,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,227.304560,648.075066,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,20.000000,NaN,1.0,1.0,1.0,1.0

`df.shape`

In [16]:
shots.shape

(472, 72)

`len()`

In [17]:
len(shots)

472

In [18]:
sample_data = range(0, 10)
len(sample_data)
# list(sample_data)

10

In [19]:
sample_data = data['Name']
len(sample_data)
# data['Name']

4

### How to Subset your Dataframe
One Column: `df[]`

Multiple Columns: `df[[ ]]`

In [20]:
shots[['pointScore']].head()

  pointScore
0        0-0
1        0-0
2        0-0
3        0-0
4       15-0

In [21]:
shots[['pointScore', 'gameScore', 'setScore']].head()

  pointScore gameScore setScore
0        0-0       0-0      0-0
1        0-0       0-0      0-0
2        0-0       0-0      0-0
3        0-0       0-0      0-0
4       15-0       0-0      0-0

### How to Filter your dataframe

`df.loc[]` and `df.iloc[]`

`df.loc[df['column'] == 'condition']`

In [22]:
shots.loc[shots['InsideOut'] == 1].head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,40-0,0-0,0-0,NaN,105620.0,1.0,105620.0,4,NaN,2,Ad,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.081819,478.803674,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-168.478341,-193.353565,NaN,1.0,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN
15,0-0,1-0,0-0,NaN,158580.0,1.0,158580.0,5,NaN,3,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-25.773075,-370.143373,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.902909,468.458503,NaN,1.0,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,2,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN
30,30-30,1-0,0-0,NaN,278220.0,NaN,NaN,9,NaN,8,Deuce,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-45.602811,475.215256,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.823628,-341.704112,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,2,NaN,Kaylan Bigun,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short

In [23]:
shots.iloc[0:5]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

### Conditional Subsetting & Querying
`&`

`|`

In [24]:
shots['serverName'].head()

0    Kaylan Bigun
1    Kaylan Bigun
2    Kaylan Bigun
3    Kaylan Bigun
4    Kaylan Bigun
Name: serverName, dtype: object

In [25]:
shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['isAce'] == 1)]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.0,201.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

`.query()`
1. Filter when the `serverName` is equal to `Kaylan Bigun`
2. Also Filter all of his Aces

Can use many conditions (==, != , >, <, >=, <=)

In [26]:
shots.query("serverName == 'Kaylan Bigun' and isAce == 1").head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.0,201.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

### Summarizing the Data (Numerical)
`.mean()`

`.max()`

`.min()`

`.std()`

`.var()`

`.quantile`

### Can also do for multiple Columns
`df[['column', 'column', ...]].mean()`

### Use the Aggregate Function

`.agg()`

`df[['column', 'column', ...]].agg(['mean', 'sum', 'max'])`

`.sum()`

`.count()`

### Summarizing the Data (Categorial)

`.unique()`

`.nunique()`

Same as len(df.unique())

`.value_counts()`

Arguments: normalize (True, False)


Find the value counts of `firstServeZone`

Find the value counts of `firstServeZone` and `firstServeIn`

### GroupBy Methods
`df.groupby()`

### Handling Missing Values
`.isna()`

`.dropna()`

`.fillna()`

### How to save/write your CSV
`.to_csv()`

### Problems to Practice Yourself!!

#### Problem 1: From the `Shot_Visuals_KaylanBigun_NathanTrouve.csv` dataset, create two tables
1. Table of the **counts** of the zones Kaylan had served into for his firstServe (including made adn missed)
1. Table of the **percentage** of the zones Kaylan had served into for his firstServe ((including made adn missed))

In [29]:
# Subsetting
# Conditional/Querying 
# value_counts()

counts = shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['firstServeIn'])]['firstServeZone'].value_counts()
percentage = counts / counts.sum() * 100
print(counts)
print(percentage)

firstServeZone
T       19
Wide    14
Body     5
Name: count, dtype: int64
firstServeZone
T       50.000000
Wide    36.842105
Body    13.157895
Name: count, dtype: float64

#### Problem 2: From the `(playsight)kaylan_usc.xlsx` dataset (Download from slack!)
Find the minimum, maximum, and average speed of Kaylan's stroke type

In [36]:
# .agg() (.max(), .mean(), .sum())
# value_counts()

shots_excel.loc[shots_excel['Player'] == 'Kaylan Bigun'].groupby('Stroke')['Speed (MPH)'].agg(['min', 'max', 'mean'])

                min         max       mean
Stroke
Backhand  25.032770   77.378082  49.743167
Feed      17.320551   21.650688  18.490169
Forehand  24.667412   88.736710  51.628206
Serve     40.868378  130.596954  88.299908
Volley    22.516716   23.382744  22.949730