## Week 2: Jupyter Notebook - Pandas Introduction/Overview
Make sure to select your Kernel before starting!

Watch the [Youtube Video](https://www.youtube.com/watch?v=DkjCaAMBGWM&t=1s) I based this notebook from!

### Import Pandas Library/Package
`import pandas as pd`

In [3]:
import pandas as pd

### Optional: Displaying your Dataframe
Don't use for big datasets

In [4]:
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.max_rows", None)     # Show all rows

### How to make a dataframe
`pd.DataFrame()`

In [6]:
data = {'Name': ['Zophie', 'Alice', 'Bob', 'Charlie'], 
        'Age': [7, 5, 3, 2],
        'Color': ['Gray', 'Black', 'Brown', 'White']
        }  

data                                                     # Called a Python Dictionary

{'Name': ['Zophie', 'Alice', 'Bob', 'Charlie'],
 'Age': [7, 5, 3, 2],
 'Color': ['Gray', 'Black', 'Brown', 'White']}

#### Create a data frame
Store the dataframe using the `pd.DataFrame()` function into a variable called `df`

In [8]:
df = pd.DataFrame(data)
df

      Name  Age  Color
0   Zophie    7   Gray
1    Alice    5  Black
2      Bob    3  Brown
3  Charlie    2  White

### Read In Datasets
`pd.read_csv()`
Read in the file from the data folder called `Shot_Visuals_KaylanBigun_NathanTrouve.csv`

Save as `shots`

In [13]:
shots = pd.read_csv("data/Shot_Visuals_KaylanBigun_NathanTrouve.csv")

`pd.read_json()`

`pd.read_excel(x, sheet_name)`

In [ ]:
shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name='Points')

,Point,Game,Set,Serve State,Match Server,Host Game Score,Guest Game Score,Point Winner,Detail,Break Point,Set Point,Favorited,Start Time,Video Time,Duration
0,1,1,1,second,host,0,0,guest,Forehand Unforced Error,False,False,False,22:45:26,27.020000,14.800000
1,2,1,1,second,host,0,15,guest,Double Fault,False,False,False,22:46:45,106.949997,1.700000
2,3,1,1,first,host,0,30,guest,Forehand Unforced Error,False,False,False,22:47:37,158.149994,3.300000
3,4,1,1,second,host,0,40,guest,Forehand Unforced Error,True,False,False,22:48:05,186.279999,12.980000
4,5,2,1,second,guest,0,0,host,Double Fault,False,False,False,22:48:42,223.880005,1.980000
5,6,2,1,second,guest,15,0,host,Double Fault,False,False,False,22:49:02,243.380005,14.770000
6,7,2,1,first,guest,30,0,host,Backhand Unforced Error,False,False,False,22:49:30,271.149994,13.930000
7,8,2,1,second,guest,40,0,host,Forehand Unforced Error,True,False,False,22:50:00,301.350006,12.730000
8,9,3,1,first,host,0,0,guest,Backhand Winner,False,False,False,22:50:40,341.079987,2.080000
9,10,3,1,first,host,0,15,guest,Forehand Unforced Error,False,False,False,22:50:57,358.859985,3.080000
10,11,3,1,second,host,0,30,host,Backhand Unforced Error,False,False,False,22:51:34,395.049988,17.100000
11,12,3,1,second,host,15,30,guest,Forehand Unforced Error,False,False,False,22:52:15,436.079987,19.480000
12,13,3,1,second,host,15,40,host,NaN,True,False,False,22:53:02,483.179993,12.880000
13,14,3,1,second,host,30,40,host,Service Winner,True,False,False,22:53:40,521.909973,16.950001
14,15,3,1,first,host,40,40,host,Backhand Unforced Error,True,False,False,22:54:31,572.479980,5.930000
15,16,4,1,first,guest,0,0,guest,Service Winner,False,False,False,22:56:05,666.140015,3.130000
16,17,4,1,first,guest,0,15,guest,Backhand Unforced Error,False,False,False,22:56:18,679.309998,4.900000
17,18,4,1,first,guest,0,30,host,Forehand Unforced Error,False,False,False,22:56:36,697.479980,5.980000
18,19,4,1,second,guest,15,30,host,Double Fault,False,False,False,22:57:02,723.539978,10.920000
19,20,4,1,second,guest,30,30,guest,Service Winner,False,False,False,22:57:36,757.340027,11.630000
20,21,4,1,second,guest,30,40,host,Double Fault,False,False,False,22:58:12,793.210022,14.050000
21,22,4,1,first,guest,40,40,host,Forehand Unforced Error,True,False,False,22:58:36,817.809998,3.450000
22,23,5,1,second,host,0,0,host,Forehand Unforced Error,False,False,False,22:59:08,849.479980,16.280001
23,24,5,1,first,host,15,0,host,Service Winner,False,False,False,22:59:57,898.340027,1.520000
24,25,5,1,second,host,30,0,guest,Backhand Unforced Error,False,False,False,23:00:17,918.409973,13.470000
25,26,5,1,first,host,30,15,host,Forehand Unforced Error,False,False,False,23:00:51,952.739990,7.370000
26,27,5,1,second,host,40,15,guest,Double Fault,False,False,False,23:01:19,980.010010,14.570000
27,28,5,1,first,host,40,30,guest,Forehand Unforced Error,False,False,False,23:01:57,1018.409973,3.770000
28,29,5,1,second,host,40,40,guest,Double Fault,True,False,False,23:02:26,1047.439941,12.370000
29,30,6,1,first,guest,0,0,host,Forehand Unforced Error,False,False,False,23:04:09,1150.040039,4.530000
30,31,6,1,first,guest,15,0,guest,Service Winner,False,False,False,23:04:31,1172.540039,2.320000
31,32,6,1,first,guest,15,15,guest,NaN,False,False,False,23:04:49,1190.369995,1.970000
32,33,6,1,first,guest,15,30,host,Forehand Unforced Error,False,False,False,23:05:09,1210.239990,5.920000
33,34,6,1,second,guest,30,30,host,Double Fault,False,False,False,23:05:31,1232.540039,9.130000
34,35,6,1,first,guest,40,30,guest,Forehand Unforced Error,True,False,False,23:06:08,1269.109985,12.030000
35,36,6,1,second,guest,40,40,host,Double Fault,True,False,False,23:06:41,1302.969971,9.800000
36,37,7,1,first,host,0,0,host,Service Winner,False,False,False,23:07:34,1355.569946,1.880000
37,38,7,1,second,host,15,0,host,Service Winner,False,False,False,23:07:57,1378.000000,10.150000
38,39,7,1,first,host,30,0,guest,Forehand Unforced Error,False,False,False,23:08:25,1406.800049,2.650000
39,40,7,1,first,host,30,15,guest,Forehand Unforced Error,False,False,False,23:08:47,1428.349976,6.400000
40,41,7,1,first,host,30,30,guest,NaN,False,False,False,23:09:19,1460.369995,14.980000
41,42,7,1,first,host,30,40,host,Service Winner,True,False,False,23:10:00,1501.439941,2.130000
42,43,7,1,second,host,40,40,guest,Forehand Unforced Error,True,False,False,23:10:23,1524.069946,16.580000
43,44,8,1,first,guest,0,0,guest,Forehand Winner,False,False,False,23:12:05,1626.939941,5.100000
44,45,8,1,first,guest,0,15,guest,Service Winner,False,False,False,23:12:29,1650.300049,1.550000
45,46,8,1,first,guest,0,30,guest,Forehand Winner,False,False,False,23:12:49,1670.069946,7.230000
46,47,8,1,first,guest,0,40,guest,Ace,False,False,False,23:13:21,1702.599976,0.430000
47,48,9,1,second,host,0,0,guest,Double Fault,False,False,False,23:13:44,1725.369995,9.770000
48,49,9,1,first,host,0,15,host,NaN,False,False,False,23:14:14,1755.099976,4.730000
49,50,9,1,first,host,15,15,guest,Forehand Unforced Error,False,False,False,23:14:44,1785.300049,9.450000
50,51,9,1,first,host,15,30,guest,Forehand Unforced Error,False,False,False,23:15:30,1831.300049,8.000000
51,52,9,1,first,host,15,40,guest,Backhand Winner,True,False,False,23:16:06,1867.500000,12.000000
52,53,10,1,second,guest,0,0,host,Forehand Winner,False,False,False,23:17:43,1964.270020,14.170000
53,54,10,1,second,guest,15,0,guest,Service Winner,False,False,False,23:18:17,1998.900024,11.450000
54,55,10,1,second,guest,15,15,guest,Backhand Unforced Error,False,False,False,23:18:48,2029.900024,13.650000
55,56,10,1,second,guest,15,30,guest,Forehand Unforced Error,False,False,False,23:19:44,2085.399902,20.150000
56,57,10,1,first,guest,15,40,host,Forehand Unforced Error,False,False,False,23:20:21,2122.459961,3.080000
57,58,10,1,second,guest,30,40,host,Forehand Unforced Error,False,False,False,23:20:43,2144.929932,27.620001
58,59,10,1,second,guest,40,40,host,Double Fault,True,False,False,23:21:36,2197.300049,15.850000
59,60,11,1,first,host,0,0,guest,Backhand Unforced Error,False,False,False,23:22:17,2238.350098,6.000000
60,61,11,1,second,host,0,15,guest,Double Fault,False,False,False,23:22:42,2263.449951,36.049999
61,62,11,1,first,host,0,30,host,NaN,False,False,False,23:23:39,2320.330078,1.920000
62,63,11,1,first,host,15,30,host,NaN,False,False,False,23:23:57,2338.060059,2.580000
63,64,11,1,first,host,30,30,host,Service Winner,False,False,False,23:24:32,2373.629883,5.170000
64,65,11,1,first,host,40,30,guest,Forehand Unforced Error,False,False,False,23:24:52,2393.939941,7.800000
65,66,11,1,first,host,40,40,guest,Forehand Winner,True,False,False,23:25:23,2424.729980,4.920000
66,67,12,1,second,guest,0,0,host,Backhand Unforced Error,False,False,False,23:26:53,2514.060059,21.780001
67,68,12,1,first,guest,15,0,guest,NaN,False,False,False,23:27:43,2564.189941,1.950000
68,69,12,1,second,guest,15,15,host,Backhand Unforced Error,False,False,False,23:28:00,2581.760010,17.280001
69,70,12,1,first,guest,30,15,guest,Forehand Winner,False,False,False,23:28:41,2622.389893,5.630000
70,71,12,1,first,guest,30,30,guest,Forehand Unforced Error,False,False,False,23:29:10,2651.360107,16.879999
71,72,12,1,first,guest,30,40,guest,Forehand Unforced Error,False,False,False,23:29:56,2697.590088,5.450000
72,73,13,2,second,host,0,0,guest,Backhand Unforced Error,False,False,False,23:32:35,2856.659912,13.170000
73,74,13,2,first,host,0,15,guest,Forehand Unforced Error,False,False,False,23:33:17,2898.419922,5.030000
74,75,13,2,second,host,0,30,guest,Forehand Unforced Error,False,False,False,23:33:43,2924.959961,11.870000
75,76,13,2,first,host,0,40,host,Service Winner,True,False,False,23:34:19,2960.120117,4.370000
76,77,13,2,second,host,15,40,guest,Forehand Unforced Error,True,False,False,23:34:38,2979.959961,11.630000
77,78,14,2,first,guest,0,0,host,Forehand Unforced Error,False,False,False,23:35:57,3058.419922,8.220000
78,79,14,2,first,guest,15,0,guest,Ace,False,False,False,23:36:23,3084.949951,0.370000
79,80,14,2,second,guest,15,15,guest,Service Winner,False,False,False,23:36:43,3104.949951,10.930000
80,81,14,2,second,guest,15,30,guest,Service Winner,False,False,False,23:37:17,3138.149902,13.180000
81,82,14,2,second,guest,15,40,guest,Backhand Unforced Error,False,False,False,23:37:53,3174.719971,15.330000
82,83,15,2,second,host,0,0,host,Forehand Unforced Error,False,False,False,23:38:32,3213.649902,30.080000
83,84,15,2,first,host,15,0,guest,NaN,False,False,False,23:39:35,3276.120117,3.500000
84,85,15,2,second,host,15,15,host,Backhand Unforced Error,False,False,False,23:40:07,3308.820068,21.719999
85,86,15,2,second,host,30,15,host,Service Winner,False,False,False,23:41:00,3361.550049,14.000000
86,87,15,2,second,host,40,15,guest,Forehand Winner,False,False,False,23:41:40,3401.250000,12.230000
87,88,15,2,first,host,40,30,host,Service Winner,False,False,False,23:42:18,3439.750000,2.700000
88,89,16,2,second,guest,0,0,guest,Forehand Winner,False,False,False,23:43:42,3523.620117,18.000000
89,90,16,2,first,guest,0,15,guest,Backhand Unforced Error,False,False,False,23:44:20,3561.750000,3.980000
90,91,16,2,first,guest,0,30,host,NaN,False,False,False,23:44:41,3582.679932,3.200000
91,92,16,2,first,guest,15,30,guest,Forehand Unforced Error,False,False,False,23:45:02,3603.750000,4.930000
92,93,16,2,first,guest,15,40,guest,Backhand Unforced Error,False,False,False,23:45:19,3620.179932,4.550000
93,94,17,2,first,host,0,0,host,Forehand Unforced Error,False,False,False,23:45:50,3651.250000,4.080000
94,95,17,2,first,host,15,0,host,Service Winner,False,False,False,23:46:17,3678.179932,1.450000
95,96,17,2,second,host,30,0,guest,Backhand Unforced Error,False,False,False,23:46:37,3698.550049,13.180000
96,97,17,2,first,host,30,15,host,Forehand Unforced Error,False,False,False,23:47:16,3737.750000,4.480000
97,98,17,2,first,host,40,15,guest,Forehand Unforced Error,False,False,False,23:47:47,3768.379883,5.950000
98,99,17,2,first,host,40,30,guest,Forehand Unforced Error,False,False,False,23:48:17,3798.929932,2.400000
99,100,17,2,second,host,40,40,guest,Backhand Winner,True,False,False,23:48:42,3823.909912,11.630000
100,101,18,2,first,guest,0,0,host,Forehand Unforced Error,False,False,False,23:50:32,3933.379883,2.550000
101,102,18,2,first,guest,15,0,host,Forehand Unforced Error,False,False,False,23:50:59,3960.810059,6.600000
102,103,18,2,second,guest,30,0,host,Double Fault,False,False,False,23:51:28,3989.679932,9.250000
103,104,18,2,first,guest,40,0,host,Backhand Winner,True,False,False,23:52:06,4027.709961,3.230000
104,105,19,2,first,host,0,0,host,Forehand Unforced Error,False,False,False,23:52:28,4049.580078,4.230000
105,106,19,2,first,host,15,0,guest,Forehand Unforced Error,False,False,False,23:52:53,4074.209961,13.620000
106,107,19,2,first,host,15,15,host,Forehand Unforced Error,False,False,False,23:53:41,4122.439941,5.770000
107,108,19,2,first,host,30,15,guest,Forehand Winner,False,False,False,23:54:15,4156.740234,1.530000
108,109,19,2,second,host,30,30,guest,NaN,False,False,False,23:54:42,4183.080078,10.200000
109,110,19,2,first,host,30,40,host,Service Winner,True,False,False,23:55:14,4215.680176,1.650000
110,111,19,2,first,host,40,40,guest,Backhand Unforced Error,True,False,False,23:55:38,4239.740234,24.080000
111,112,20,2,first,guest,0,0,guest,Forehand Unforced Error,False,False,False,23:57:40,4361.680176,4.050000
112,113,20,2,first,guest,0,15,guest,Forehand Winner,False,False,False,23:58:10,4391.129883,4.780000
113,114,20,2,first,guest,0,30,host,Backhand Unforced Error,False,False,False,23:58:34,4415.779785,5.200000
114,115,20,2,first,guest,15,30,guest,Backhand Winner,False,False,False,23:58:54,4435.919922,6.120000
115,116,20,2,first,guest,15,40,guest,Ace,False,False,False,23:59:18,4459.669922,1.100000

### Basic Functions for Quick Analysis
`df.head()`

Gives you the **FIRST** 5 observations/rows
- If you put a number within the parentheses you will get that number of rows

`df.tail()`
Gives you the **LAST** 5 observations/rows

`df.sample()`

Gives you a **RANDOM** observation sample

Arguments: frac, random_state

`df.columns`

Gives you all the column names of your dataset

`df.index`

Gives you the index values in the dataframe

Use the `list()` function to see all the numbers

`df.info()`

`df.describe()`

`df.shape`

`len()`

In [ ]:
sample_data = range(0, 10)
len(sample_data)
# list(sample_data)

In [ ]:
sample_data = data['Name']
len(sample_data)
# data['Name']

### How to Subset your Dataframe
One Column: `df[]`

Multiple Columns: `df[[ ]]`

### How to Filter your dataframe

`df.loc[]` and `df.iloc[]`

`df.loc[df['column'] == 'condition']`

### Conditional Subsetting & Querying
`&`

`|`

`.query()`
1. Filter when the `serverName` is equal to `Kaylan Bigun`
2. Also Filter all of his Aces

Can use many conditions (==, != , >, <, >=, <=)

### Summarizing the Data (Numerical)
`.mean()`

`.max()`

`.min()`

`.std()`

`.var()`

`.quantile`

### Can also do for multiple Columns
`df[['column', 'column', ...]].mean()`

### Use the Aggregate Function

`.agg()`

`df[['column', 'column', ...]].agg(['mean', 'sum', 'max'])`

`.sum()`

`.count()`

### Summarizing the Data (Categorial)

`.unique()`

`.nunique()`

Same as len(df.unique())

`.value_counts()`

Arguments: normalize (True, False)


Find the value counts of `firstServeZone`

Find the value counts of `firstServeZone` and `firstServeIn`

### GroupBy Methods
`df.groupby()`

### Handling Missing Values
`.isna()`

`.dropna()`

`.fillna()`

### How to save/write your CSV
`.to_csv()`

### Problems to Practice Yourself!!

#### Problem 1: From the `Shot_Visuals_KaylanBigun_NathanTrouve.csv` dataset, create two tables
1. Table of the **counts** of the zones Kaylan had served into for his firstServe (including made adn missed)
1. Table of the **percentage** of the zones Kaylan had served into for his firstServe ((including made adn missed))

In [ ]:
# Subsetting
# Conditional/Querying 
# value_counts()

#### Problem 2: From the `(playsight)kaylan_usc.xlsx` dataset (Download from slack!)
Find the minimum, maximum, and average speed of Kaylan's stroke type

In [ ]:
# .agg() (.max(), .mean(), .sum())
# value_counts()